# fly.toml app configuration file generated for ms-payment-gateway-v1 on 2024-04-23T10:47:59-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ms-payment-gateway-v1'
primary_region = 'bog'

[build]
  image = 'jamp1992/ms-payment-gateway:v11'

[env]
  ACCESS_TOKEN = 'TEST-3646189138608415-120216-9622114fbecb7d017cdb967f65283ee3-1527749756'
  ACCOUNT_ID = '1015033'
  AMOUNT_ANTECEDENT_REPORT = '23789'
  AMOUNT_SEARCH_PERSON = '11889'
  API_KEY = '37zYaBtoMWAM253MoOy29bS5Th'
  BD_TRANSACTION = 'http://bd-transaction-v1.internal:8080'
  CONFIRMATION_URL = 'https://invexdijin.com/#/after-payment/'
  CURRENCY = 'COP'
  DESCRIPTION = 'TestPAYU'
  ITEM_PRICE = '1000'
  MERCHANT_ID = '1006279'
  MS_ANTECEDENT_REPORT = 'http://ms-antecedent-report-v1.internal:8080'
  RESPONSE_URL = 'https://invexdijin.com/#/after-payment/'
  TAX_ANTECEDENT_REPORT = '3799'
  TAX_RETURN_BASE_ANTECEDENT_REPORT = '19990'
  TAX_RETURN_BASE_SEARCH_PERSON = '9990'
  TAX_SEARCH_PERSON = '1899'
  TEST_PROPERTY = '0'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
